language: r
cache:
  packages: true
  directories:
  - _book

apt:
  packages:
    - libpoppler-cpp-dev
    - libapparmor-dev

r_packages:
  - kableExtra
  - readtext
  - stringr
  - dplyr
  - ggplot2
  - pdftools
  - svglite

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
