language: r
cache:
  packages: true
  directories:
  - _book

before_script:
  - sudo add-apt-repository -y ppa:cran/poppler
  - sudo apt-get update
  - sudo apt-get install -y libpoppler-cpp-dev
  - sudo apt-get install libapparmor-dev
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

r_packages:
  - pdftools
  - kableExtra
  - readtext
  - stringr
  - dplyr
  - ggplot2
  - svglite

script:
  - ./_build.sh
  - ./_deploy.sh
