language: r
cache:
  packages: true
  directories:
  - _book
  
r_packages:
  - kableExtra
  - readtext
  - stringr
  - dplyr
  - ggplot2
  - pdftools
  - svglite

before_script:
  - sudo apt-get install libpoppler-cpp-dev
  - sudo apt-get install libapparmor-dev
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
