language: r
pandoc_version: 1.19.2.1

env:
  global:
    - secure: ffc85e7fa413af3c50eda2f8d9befc1d0aba945b

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
