language: r

apt_packages:
  - libpoppler-cpp-dev
  - libapparmor-dev

before_script:
  - sudo apt-get install libpoppler-cpp-dev
  - sudo apt-get install libapparmor-dev
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
